name: watmap
description: "A app help you hang around uwaterloo"
publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0
  get_it: ^8.0.3
  drift_flutter: ^0.2.4
  fluttertoast: ^8.2.12
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.8.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  json_serializable: ^6.9.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LaunchIcon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/campusMap.png
    - assets/lang/appInfo.json
    - config/properties.env

